#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 2
#define VERSION_BUILD 5

#define STRINGIFY(s) #s
#define TOSTRING(s) STRINGIFY(s)

#define VERSION_STRING TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_PATCH) "." TOSTRING(VERSION_BUILD)

#define BUILD_TIME __DATE__ " " __TIME__

#endif // VERSION_H
